name: Auto-merge Codex PRs
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  pull-requests: write
  contents: write
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Enable Auto-Merge
        run: gh pr merge --merge --auto ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}