name: Deploy to Bluehost via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checks out your repository's code so the workflow can access it.
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. This step uses the correct, dedicated SFTP action.
      - name: SFTP Deploy
        # This is a popular and well-maintained SFTP-specific action.
        uses: easingthemes/sftp-deploy@v3.2.0
        with:
          # Your SSH private key, stored as a repository secret.
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # Your server's IP address (maps to your FTP_SERVER secret).
          REMOTE_HOST: ${{ secrets.FTP_SERVER }}
          
          # Your cPanel username (maps to your FTP_USERNAME secret).
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          
          # The destination directory on your Bluehost server.
          TARGET: /home3/cpwwhamy/public_html/llm/