name: Deploy to Bluehost Server

on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Files to Bluehost
    steps:
      # Step 1: Check out your repository code. Using v4 is the current best practice.
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Deploy the files using the action you found.
      - name: Deploy to Server via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          # This must be your cPanel username, not 'root'.
          # It's correctly pulling from the secret you already created.
          username: ${{ secrets.FTP_USERNAME }}
          
          # Your server's IP address from your GitHub secret.
          server: ${{ secrets.FTP_SERVER }}
          
          # Your private key for authentication.
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # This tells the action to upload ALL files and folders from your
          # repository's root directory.
          local_path: './*'
          
          # The absolute path to your subdomain's folder on the server.
          # This is the full path we identified from your previous logs.
          remote_path: '/home3/cpwwhamy/public_html/llm/'
          
          # Optional: You can keep these extra arguments.
          sftpArgs: '-o ConnectTimeout=5'