name: Deploy to Bluehost Server

on: [push]

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: Deploy Files to Bluehost
    steps:
      # Use the latest major version of the checkout action
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Server via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          # Your cPanel username from GitHub Secrets
          username: ${{ secrets.FTP_USERNAME }}
          
          # Your server's IP address from GitHub Secrets
          server: ${{ secrets.FTP_SERVER }}
          
          # The SFTP port is always 22 for Bluehost
          port: 22
          
          # Your SSH private key (which you just fixed and re-saved)
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # The passphrase for your SSH key, if it has one
          ssh_passphrase: ${{ secrets.SSH_PASSPHRASE }}

          # This uploads ALL files from your repository's root
          local_path: './*'
          
          # The correct, absolute path to your deployment folder on Bluehost
          remote_path: '/home3/cpwwhamy/public_html/llm/'
          
          # This is a good setting to explicitly use SFTP.
          sftp_only: true