# Name of your workflow
name: Deploy to Bluehost Subdomain

# Run this workflow every time you push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  # The job ID
  ftp-deploy:
    # The runner (virtual machine) to run the job on
    runs-on: ubuntu-latest
    
    steps:
      # 1. Check out your repository code so the job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. The main deploy step using a popular FTP/SFTP action
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          protocol: sftp  # Use 'ftp' for an insecure connection, but 'sftp' is recommended for security
          port: 22  # Default port for SFTP; use 21 for FTP
          # Use 'sftp' for a secure connection
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          
          # The destination folder on your server (the subdomain's document root)
          server-dir: /public_html/llm/
          
          # Don't delete existing files that aren't in the repo (like .htaccess if needed)
          dangerous-clean-slate: false