# Name of your workflow
name: Deploy to Bluehost via SFTP

# Run this workflow every time you push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # The runner (virtual machine) to run the job on
    runs-on: ubuntu-latest
    
    steps:
      # 1. Check out your repository code so the job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. This is the new, correct SFTP deployment step
      - name: SFTP Deploy to Bluehost
        # Use the appleboy/sftp-action, which fully supports SFTP
        uses: appleboy/sftp-action@v1.0.3
        with:
          # Your server's IP address from GitHub Secrets
          host: ${{ secrets.FTP_SERVER }}
          
          # Your cPanel username from GitHub Secrets
          username: ${{ secrets.FTP_USERNAME }}
          
          # Use the SSH Private Key for secure authentication
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          # The passphrase for your SSH key, if you have one
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          
          # The SFTP port is always the SSH port
          port: 22
          
          # The source directory from your repo to upload (./ is everything)
          source: "./"
          
          # The destination directory on your Bluehost server
          target: /public_html/llm/